# datapoint_mapping.py — fully cleaned version
# Each datapoint contains only: name, group, type

DATA_POINT_MAPPING = {
    '0x0000': {'name': 'Firmware Version', 'group': 'System', 'type': 'EB_TYPE_INT32'},

    '0x0001': {'name': 'Setpoint Resistor', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},

    '0x0002': {'name': 'Fan Duty Cycle', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x0003': {'name': 'Measured Fan Speed', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},

    '0x0100': {'name': 'Switch Heater Current Setpoint', 'group': 'System', 'type': 'EB_TYPE_FLOAT'},
    '0x0101': {'name': 'Measured Switch Heater Current', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x0102': {'name': 'Shim Switch Heater Channel', 'group': 'System', 'type': 'EB_TYPE_UINT32'},

    '0x0200': {'name': 'BCM Status', 'group': 'System', 'type': 'EB_TYPE_UINT16'},
    '0x0201': {'name': 'BCM VIN Meas', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x0202': {'name': 'BCM VOUT Meas', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x0203': {'name': 'BCM IIN Meas', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x0204': {'name': 'BCM IOUT Meas', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x0205': {'name': 'BCM Temp', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x0206': {'name': 'BCM Timstamp', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x0207': {'name': 'Vicor I2C Init Counter', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x0208': {'name': 'Vicor I2C Arb Lost Counter', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x0300': {'name': 'System I2C Init Counter', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x0301': {'name': 'System I2C Arb Lost Counter', 'group': 'System', 'type': 'EB_TYPE_INT32'},

    '0x1000': {'name': 'Filtered Module Currents', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1001': {'name': 'Filtered Bus Voltage', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1002': {'name': 'Filtered Terminal Voltage', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1003': {'name': 'Filtered End of Line Voltage', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1004': {'name': 'Filtered Main Voltage', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1100': {'name': 'I Main Set', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1101': {'name': 'U Main Set', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1102': {'name': 'Request Dissipation', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x1103': {'name': 'I Main Ref', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1104': {'name': 'I Main Rate of Change ', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1105': {'name': 'U Main Rate of Change', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1106': {'name': 'U Main Ref', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1107': {'name': 'Main Coil CV/CC Mode', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x1108': {'name': 'I Main Integrator', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1109': {'name': 'U Main Integrator', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x110A': {'name': 'PI Ctrl U Out', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x110B': {'name': 'PI Ctrl Duty Cycle', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x110C': {'name': 'Pi U Main Set', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x110D': {'name': 'PI I Main Set', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1111': {'name': 'U lead max Setpoint', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1112': {'name': 'U lead min Setpoint', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1200': {'name': 'I Shim Set', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1201': {'name': 'I Shim Ref', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1202': {'name': 'U Shim Max', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1203': {'name': 'I Shim Rate', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1300': {'name': 'Shim Current Control P Gain', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1301': {'name': 'Shim Current Control I Freq', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x1400': {'name': 'PM Protection Triggered', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x1401': {'name': 'PM Protection Current Limit', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},

    '0x2000': {'name': 'Current Operating Mode', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x2001': {'name': 'Request Operating Mode', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x2002': {'name': 'Request Shim Ch', 'group': 'System', 'type': 'EB_TYPE_UINT32'},

    '0x3000': {'name': 'PM Req Pending', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3001': {'name': 'PM Req Fault', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3002': {'name': 'PM Alarm', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3003': {'name': 'PM Number Alarms', 'group': 'System', 'type': 'EB_TYPE_INT32'},
    '0x3100': {'name': 'PM Meas Time Stamp', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3101': {'name': 'PM Meas Vout A', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x3102': {'name': 'PM Meas Vout B', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x3103': {'name': 'PM Meas V HB 1', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x3104': {'name': 'PM Meas Temp A', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x3105': {'name': 'PM Meas Temp B', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x3106': {'name': 'PM Meas Temp MCU', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x3107': {'name': 'PM Fuse On/Off', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3108': {'name': 'PM Fuse Protection', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3109': {'name': 'PM Meas Input Current', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x3200': {'name': 'PM Stat Time Stamp', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3201': {'name': 'PM Stat Temp Warn A', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3202': {'name': 'PM Stat Temp Warn B', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3203': {'name': 'PM Stat Switch Closed', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3204': {'name': 'PM Stat SIC ZCD', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3205': {'name': 'PM Stat Fault A', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3206': {'name': 'PM Stat Fault B', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3300': {'name': 'PM Err Count Reset', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x3301': {'name': 'PM Err Counting Since', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3302': {'name': 'PM EC Rx Ring Buf Overflow', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3303': {'name': 'PM EC Decoder Overflow', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3304': {'name': 'PM EC Decoder Invalid Char', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3305': {'name': 'PM EC Rx Msg Short', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3306': {'name': 'PM EC Rx Msg CRC', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3307': {'name': 'PM EC Rx Msg Format', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x3308': {'name': 'PM EC Rx Msg Type', 'group': 'System', 'type': 'EB_TYPE_UINT32'},
    '0x4000': {'name': 'PWM Duty Cycle A', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x4001': {'name': 'PWM Duty Cycle B', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x4002': {'name': 'PWM Enable', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x5000': {'name': 'ADC Mode', 'group': 'System', 'type': 'EB_TYPE_INT8'},
    '0x5001': {'name': 'ADC Samples Integer', 'group': 'System', 'type': 'EB_TYPE_INT32'},
    '0x5002': {'name': 'ADC Samples Physical', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x5003': {'name': 'Main Shunt Resistance', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x5004': {'name': 'Main Shunt Resistance Setpoint', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x5005': {'name': 'Shim Shunt Resistance', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x5006': {'name': 'Shim Shunt Resistance Setpoint', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x5100': {'name': 'ADC Offsets Integer', 'group': 'System', 'type': 'EB_TYPE_INT32'},
    '0x5101': {'name': 'ADC Offsets Physical', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x5102': {'name': 'ADC Offset Calibration Status', 'group': 'System', 'type': 'EB_TYPE_INT8'},
    '0x5103': {'name': 'ADC Offset Calibration Start', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x5200': {'name': 'PGA Clear Errors', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x5201': {'name': 'PGA IAR Error', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x5202': {'name': 'PGA ICA Error', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x5203': {'name': 'PGA OUT Error', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x5204': {'name': 'PGA GAIN Error', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x5205': {'name': 'PGA IOV Error', 'group': 'System', 'type': 'EB_TYPE_BOOL'},
    '0x5210': {'name': 'PGA Gain', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x6001': {'name': 'T main shunt p1', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x6002': {'name': 'T main shunt p2', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x6003': {'name': 'T shim shunt', 'group': 'System', 'type': 'EB_TYPE_DOUBLE'},
    '0x2100': {'name': 'DPID_OC_TIMEOUT_MS', 'group': 'System', 'type': 'EB_TYPE_UINT32'}
}
